#include<bits/stdc++.h>
#include<windows.h>
#define KEY_DOWN(VK_NONAME) ((GetAsyncKeyState(VK_NONAME) & 0x8000) ? 1:0)
using namespace std;
long long iii=21,jjj=5,dd,i,j,i1,i2,j2,i3,j3,fs=0,maxfs=0,j11,d,panding=0,suiji,mapp[100][100],yanshi=10,suiji1,suiji2,UI=1,gameover=0,xz,nx,ny,gg,ysld;
char a[100][100],fuzhuxian=' ',fangkuai='#';//经典:#    简单:!     普通:*    困难:^    非常困难:`    地狱:) and ( and .
void qingping(long long x,long long y)
{
	HANDLE handle=GetStdHandle(STD_OUTPUT_HANDLE);
	COORD pos;
	pos.X=x;
	pos.Y=y;
	SetConsoleCursorPosition(handle,pos);
}
void SetColorAndBackground(int ForgC,int BackC)//SetColorAndBackground(7,0);	上色 
{
	WORD wColor=((BackC&0x0F)<<4)+(ForgC&0x0F);
	SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE),wColor);
}
void cou()
{ 
	qingping(0,0);
	for(int ii=1;ii<=22;ii++)
	{
		for(int jj=1;jj<=19;jj++)
		{
			if(suiji1==1)
			{
				if(ii==4&&jj==14||ii==4&&jj==15||ii==4&&jj==16||ii==4&&jj==17)
				{
					SetColorAndBackground(3,0);
					cout<<fangkuai;
					SetColorAndBackground(7,0);
					continue;
				}
			}
			if(suiji2==1)
			{
				if(ii==9&&jj==14||ii==9&&jj==15||ii==9&&jj==16||ii==9&&jj==17)
				{
					SetColorAndBackground(3,0);
					cout<<fangkuai;
					SetColorAndBackground(7,0);
					continue;
				}
			}
			if(suiji1==2)
			{
				if(ii==4&&jj==15||ii==4&&jj==16||ii==5&&jj==15||ii==5&&jj==16)
				{
					SetColorAndBackground(6,0);
					cout<<fangkuai;
					SetColorAndBackground(7,0);
					continue;
				}
			}
			if(suiji2==2)
			{
				if(ii==9&&jj==15||ii==9&&jj==16||ii==10&&jj==15||ii==10&&jj==16)
				{
					SetColorAndBackground(6,0);
					cout<<fangkuai;
					SetColorAndBackground(7,0);
					continue;
				}
			}
			if(suiji1==3)
			{
				if(ii==4&&jj==15||ii==4&&jj==16||ii==5&&jj==16||ii==5&&jj==17)
				{
					SetColorAndBackground(2,0);
					cout<<fangkuai;
					SetColorAndBackground(7,0);
					continue;
				}
			}
			if(suiji2==3)
			{
				if(ii==9&&jj==15||ii==9&&jj==16||ii==10&&jj==16||ii==10&&jj==17)
				{
					SetColorAndBackground(2,0);
					cout<<fangkuai;
					SetColorAndBackground(7,0);
					continue;
				}
			}
			if(suiji1==4)
			{
				if(ii==5&&jj==15||ii==5&&jj==16||ii==4&&jj==16||ii==4&&jj==17)
				{
					SetColorAndBackground(4,0);
					cout<<fangkuai;
					SetColorAndBackground(7,0);
					continue;
				}
			}
			if(suiji2==4)
			{
				if(ii==10&&jj==15||ii==10&&jj==16||ii==9&&jj==16||ii==9&&jj==17)
				{
					SetColorAndBackground(4,0);
					cout<<fangkuai;
					SetColorAndBackground(7,0);
					continue;
				}
			}
			if(suiji1==5)
			{
				if(ii==4&&jj==16||ii==5&&jj==15||ii==5&&jj==16||ii==5&&jj==17)
				{
					SetColorAndBackground(5,0);
					cout<<fangkuai;
					SetColorAndBackground(7,0);
					continue;
				}
			}
			if(suiji2==5)
			{
				if(ii==9&&jj==16||ii==10&&jj==15||ii==10&&jj==16||ii==10&&jj==17)
				{
					SetColorAndBackground(5,0);
					cout<<fangkuai;
					SetColorAndBackground(7,0);
					continue;
				}
			}
			if(suiji1==6)
			{
				if(ii==4&&jj==17||ii==5&&jj==15||ii==5&&jj==16||ii==5&&jj==17)
				{
					SetColorAndBackground(1,0);
					cout<<fangkuai;
					SetColorAndBackground(7,0);
					continue;
				}
			}
			if(suiji2==6)
			{
				if(ii==9&&jj==17||ii==10&&jj==15||ii==10&&jj==16||ii==10&&jj==17)
				{
					SetColorAndBackground(1,0);
					cout<<fangkuai;
					SetColorAndBackground(7,0);
					continue;
				}
			}
			if(suiji1==7)
			{
				if(ii==4&&jj==15||ii==5&&jj==15||ii==5&&jj==16||ii==5&&jj==17)
				{
					SetColorAndBackground(12,0);
					cout<<fangkuai;
					SetColorAndBackground(7,0);
					continue;
				}
			}
			if(suiji2==7)
			{
				if(ii==9&&jj==15||ii==10&&jj==15||ii==10&&jj==16||ii==10&&jj==17)
				{
					SetColorAndBackground(12,0);
					cout<<fangkuai;
					SetColorAndBackground(7,0);
					continue;
				}
			}
			if(ii==12&&jj==13)
			{
				cout<<"W 旋转";
				jj=18;
				continue;
			}
			if(ii==13&&jj==13)
			{
				cout<<"A 左移";
				jj=18;
				continue;
			}
			if(ii==14&&jj==13)
			{
				cout<<"D 右移";
				jj=18;
				continue;
			}
			if(ii==15&&jj==13)
			{
				cout<<"S 下降";
				jj=18;
				continue;
			}
			if(ii==16&&jj==13)
			{
				cout<<"J 急降";
				jj=18;
				continue;
			}
			if(ii==17&&jj==13)
			{
				cout<<"######";
				jj=18;
				continue;
			}
			if(ii==18&&jj==13)
			{
				cout<<"↑跳跃";
				jj=18;
				continue;
			}
			if(ii==19&&jj==13)
			{
				cout<<"←左移";
				jj=18;
				continue;
			}
			if(ii==20&&jj==13)
			{
				cout<<"→右移";
				jj=18;
				continue;
			}
			if(ii==21&&jj==13)
			{
				cout<<"达终点";
				jj=18;
				continue;
			}
			if(a[ii][jj]==' ')
			{
				SetColorAndBackground(7,0);
			}
			if(mapp[ii][jj]==1||suiji==1&&ii==i&&jj==j||suiji==1&&ii==i1&&jj==j11||suiji==1&&ii==i2&&jj==j2||suiji==1&&ii==i3&&jj==j3)
			{
				SetColorAndBackground(3,0);
				if(ysld>=1&&a[ii][jj]!=fangkuai)
				{
					SetColorAndBackground(3,3);
				}
			}
			if(mapp[ii][jj]==2||suiji==2&&ii==i&&jj==j||suiji==2&&ii==i1&&jj==j11||suiji==2&&ii==i2&&jj==j2||suiji==2&&ii==i3&&jj==j3)
			{
				SetColorAndBackground(6,0);
				if(ysld>=1&&a[ii][jj]!=fangkuai)
				{
					SetColorAndBackground(6,6);
				}
			}
			if(mapp[ii][jj]==3||suiji==3&&ii==i&&jj==j||suiji==3&&ii==i1&&jj==j11||suiji==3&&ii==i2&&jj==j2||suiji==3&&ii==i3&&jj==j3)
			{
				SetColorAndBackground(2,0);
				if(ysld>=1&&a[ii][jj]!=fangkuai)
				{
					SetColorAndBackground(2,2);
				}
			}
			if(mapp[ii][jj]==4||suiji==4&&ii==i&&jj==j||suiji==4&&ii==i1&&jj==j11||suiji==4&&ii==i2&&jj==j2||suiji==4&&ii==i3&&jj==j3)
			{
				SetColorAndBackground(4,0);
				if(ysld>=1&&a[ii][jj]!=fangkuai)
				{
					SetColorAndBackground(4,4);
				}
			}
			if(mapp[ii][jj]==5||suiji==5&&ii==i&&jj==j||suiji==5&&ii==i1&&jj==j11||suiji==5&&ii==i2&&jj==j2||suiji==5&&ii==i3&&jj==j3)
			{
				SetColorAndBackground(5,0);
				if(ysld>=1&&a[ii][jj]!=fangkuai)
				{
					SetColorAndBackground(5,5);
				}
			}
			if(mapp[ii][jj]==6||suiji==6&&ii==i&&jj==j||suiji==6&&ii==i1&&jj==j11||suiji==6&&ii==i2&&jj==j2||suiji==6&&ii==i3&&jj==j3)
			{
				SetColorAndBackground(1,0);
				if(ysld>=1&&a[ii][jj]!=fangkuai)
				{
					SetColorAndBackground(1,1);
				}
			}
			if(mapp[ii][jj]==7||suiji==7&&ii==i&&jj==j||suiji==7&&ii==i1&&jj==j11||suiji==7&&ii==i2&&jj==j2||suiji==7&&ii==i3&&jj==j3)
			{
				SetColorAndBackground(12,0);
				if(ysld>=1&&a[ii][jj]!=fangkuai)
				{
					SetColorAndBackground(12,12);
				}
			}
			if(mapp[ii][jj]==123)
			{
				SetColorAndBackground(14,14);
			}
			cout<<a[ii][jj];
			if(a[ii][jj]==' '&&mapp[ii][jj]!=123)
			{
				mapp[ii][jj]=0;
			}
			SetColorAndBackground(7,0);
		}
		cout<<endl;
	}
	cout<<"得分:"<<fs<<endl<<"最高得分:"<<maxfs<<endl;
}
void go()
{
	dd=0;
	if(KEY_DOWN(VK_LEFT)&&a[iii][jjj-1]!=fangkuai)
	{
		a[iii][jjj]=' ';
		a[iii][jjj-1]='@';
		jjj--;
		dd=1;
	}
	if(KEY_DOWN(VK_RIGHT)&&a[iii][jjj+1]!=fangkuai)
	{
		a[iii][jjj]=' ';
		a[iii][jjj+1]='@';
		jjj++;
		dd=1;
	}
	if(dd==1)
	{
		cou();
	}
}
void block1()
{
	if(i==3)
	{
		j=5,j11=6,j2=7,j3=8,panding=0;
		a[i][j]=fangkuai,a[i][j11]=fangkuai,a[i][j2]=fangkuai,a[i][j3]=fangkuai;
		_sleep(100);
	}
	while(1)
	{
		if(panding==0)
		{
			if(a[i+1][j]!=fuzhuxian||a[i1+1][j11]!=fuzhuxian||a[i2+1][j2]!=fuzhuxian||a[i3+1][j3]!=fuzhuxian)
			{
				break;
			}
			_sleep(100);
			a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
			i++,i1++,i2++,i3++;
			a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
		}
		if(panding==1)
		{
			if(a[i3+1][j3]!=fuzhuxian)
			{
				break;
			}
			_sleep(100);
			a[i][j]=fuzhuxian,i++,i1++,i2++,a[++i3][j]=fangkuai;
		}
		if(ysld==1)
		{
			int aaaa1=i,bbbb1=i1,cccc1=i2,dddd1=i3,aaaa2=j,bbbb2=j11,cccc2=j2,dddd2=j3;
			if(panding==1)
			{
				while(a[dddd1+1][dddd2]==fuzhuxian)
				{
					aaaa1++,bbbb1++,cccc1++,dddd1++;
				}
			}
			else
			{
				while(a[cccc1+1][cccc2]==fuzhuxian&&a[dddd1+1][dddd2]==fuzhuxian&&a[aaaa1+1][aaaa2]==fuzhuxian&&a[bbbb1+1][bbbb2]==fuzhuxian)
				{
					aaaa1++,bbbb1++,cccc1++,dddd1++;
				}
			}
			mapp[aaaa1][aaaa2]=1,mapp[bbbb1][bbbb2]=1,mapp[cccc1][cccc2]=1,mapp[dddd1][dddd2]=1;
		}
		cou();
		for(int ii=1;ii<=yanshi;ii++)
		{
			if(xz==2)
			{
				go();
				if(KEY_DOWN(VK_UP))
				{
					for(int kk=1;kk<=3;kk++)
					{
						if(a[iii-1][jjj]==fangkuai)
						{
							break;
						}
						iii--;
						a[iii+1][jjj]=' ';
						a[iii][jjj]='@';
						cou();
						go();
						_sleep(100);
						if(iii==nx&&jjj==ny)
						{
							system("color E");
							cout<<"nbnbnb gg";gg=1;
							_sleep(2000);
							SetColorAndBackground(7,0);
							return;
						}
					}
				}
				while(1)
				{
					if(a[iii+1][jjj]=='#')
					{
						break;
					}
					iii++;
					a[iii-1][jjj]=' ';
					a[iii][jjj]='@';
					cou();
					_sleep(100);
					go();
					if(iii==nx&&jjj==ny)
					{
						system("color E");
						cout<<"nbnbnb gg";gg=1;
						_sleep(2000);
						SetColorAndBackground(7,0);
						return;
					}
				}
			}
			d=0;
			_sleep(100);
			if(KEY_DOWN('A'))
			{
				d=1;
				if(panding==0&&a[i][j-1]!=fangkuai)
				{
					a[i3][j3]=fuzhuxian;
				  	j--,j11--,j2--,j3--;
				  	a[i][j]=fangkuai;
				}
				if(panding==1&&a[i][j-1]!=fangkuai&&a[i1][j11-1]!=fangkuai&&a[i2][j2-1]!=fangkuai&&a[i3][j3-1]!=fangkuai)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
				  	j--,j11--,j2--,j3--;
				  	a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
			}
			if(KEY_DOWN('D'))
			{
				d=1;
				if(panding==0&&a[i3][j3+1]!=fangkuai)
				{
					a[i][j]=fuzhuxian;
				  	j++,j11++,j2++,j3++;
				  	a[i3][j3]=fangkuai;
				}
				if(panding==1&&a[i][j+1]!=fangkuai&&a[i1][j11+1]!=fangkuai&&a[i2][j2+1]!=fangkuai&&a[i3][j3+1]!=fangkuai)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
				  	j++,j11++,j2++,j3++;
				  	a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
			}
			if(KEY_DOWN('W'))
			{
				d=1;
				panding++;
				if(panding==2)
				{
					if(a[i3][j3+2]!=fangkuai&&a[i][j+2]!=fangkuai&&a[i1][j11+2]!=fangkuai&&a[i2][j2+2]!=fangkuai&&a[i3][j3+1]!=fangkuai&&a[i][j+1]!=fangkuai&&a[i1][j11+1]!=fangkuai&&a[i2][j2+1]!=fangkuai&&a[i][j-1]!=fangkuai&&a[i1][j11-1]!=fangkuai&&a[i2][j2-1]!=fangkuai&&a[i3][j3-1]!=fangkuai)
					{
						a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
						i+=2,j--,i1++,j2++,j3+=2,i3--;
						a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
						panding=0;
					}
					else
					{
						panding=1; 
					}
				}
				else
				{
					if(panding==1&&a[i1-1][j11]!=fangkuai&&a[i1-2][j11]!=fangkuai)
					{
						a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
						i-=2,j++,i1--,j2--,j3-=2,i3++;
						a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
					}
					else
					{
						panding=0;
					}
				}
			}
			if(KEY_DOWN('J'))
			{
				d=1;
				if(panding==0)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
					while(a[i+1][j]==fuzhuxian&&a[i1+1][j11]==fuzhuxian&&a[i2+1][j2]==fuzhuxian&&a[i3+1][j3]==fuzhuxian)
					{
						i++,i1++,i2++,i3++;
					}
					a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
				if(panding==1)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
					while(a[i3+1][j3]==fuzhuxian)
					{
						i++,i1++,i2++,i3++;
					}		
					a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
				return;
			}
			if(KEY_DOWN('S'))
			{
				yanshi=1;
			}
			else
			{
				yanshi=10;
			}
			if(d==1)
			{
				if(ysld==1)
				{
					int aaaa1=i,bbbb1=i1,cccc1=i2,dddd1=i3,aaaa2=j,bbbb2=j11,cccc2=j2,dddd2=j3;
					if(panding==1)
					{
						while(a[dddd1+1][dddd2]==fuzhuxian)
						{
							aaaa1++,bbbb1++,cccc1++,dddd1++;
						}
					}
					else
					{
						while(a[cccc1+1][cccc2]==fuzhuxian&&a[dddd1+1][dddd2]==fuzhuxian&&a[aaaa1+1][aaaa2]==fuzhuxian&&a[bbbb1+1][bbbb2]==fuzhuxian)
						{
							aaaa1++,bbbb1++,cccc1++,dddd1++;
						}
					}
					mapp[aaaa1][aaaa2]=1,mapp[bbbb1][bbbb2]=1,mapp[cccc1][cccc2]=1,mapp[dddd1][dddd2]=1;
				}
				cou();
			}
		}
	}
}
void block2()
{
	if(i==2)
	{
		j=6,j11=7,j2=6,j3=7;
		a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
	}
	while(a[i2+1][j2]==fuzhuxian&&a[i3+1][j3]==fuzhuxian)
	{
		_sleep(100);
		a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
		i++,i1++,i2++,i3++;
		a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
		if(ysld==1)
		{
			int aaaa1=i,bbbb1=i1,cccc1=i2,dddd1=i3,aaaa2=j,bbbb2=j11,cccc2=j2,dddd2=j3;
			while(a[cccc1+1][cccc2]==fuzhuxian&&a[dddd1+1][dddd2]==fuzhuxian)
			{
				aaaa1++,bbbb1++,cccc1++,dddd1++;
			}
			mapp[aaaa1][aaaa2]=2,mapp[bbbb1][bbbb2]=2,mapp[cccc1][cccc2]=2,mapp[dddd1][dddd2]=2;
		}
		cou();
		for(int ii=1;ii<=yanshi;ii++)
		{
			if(xz==2)
			{
				go();
				if(KEY_DOWN(VK_UP))
				{
					for(int kk=1;kk<=3;kk++)
					{
						if(a[iii-1][jjj]==fangkuai)
						{
							break;
						}
						iii--;
						a[iii+1][jjj]=' ';
						a[iii][jjj]='@';
						cou();
						go();
						_sleep(100);
						if(iii==nx&&jjj==ny)
						{
							system("color E");
							cout<<"nbnbnb gg";gg=1;
							_sleep(2000);
							SetColorAndBackground(7,0);
							return;
						}
					}
				}
				while(1)
				{
					if(a[iii+1][jjj]=='#')
					{
						break;
					}
					iii++;
					a[iii-1][jjj]=' ';
					a[iii][jjj]='@';
					cou();
					_sleep(100);
					go();
					if(iii==nx&&jjj==ny)
					{
						system("color E");
						cout<<"nbnbnb gg";gg=1;
						_sleep(2000);
						SetColorAndBackground(7,0);
						return;
					}
				}
			}
			d=0;
			_sleep(100);
			if(KEY_DOWN('A')&&a[i][j-1]!=fangkuai&&a[i2][j2-1]!=fangkuai)
			{
				d=1;
				a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
			  	j--,j11--,j2--,j3--;
			  	a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
			}
			if(KEY_DOWN('D')&&a[i1][j11+1]!=fangkuai&&a[i3][j3+1]!=fangkuai)
			{
				d=1;
				a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
			  	j++,j11++,j2++,j3++;
			  	a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
			}
			if(KEY_DOWN('J'))
			{
				d=1;
				a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
				while(a[i2+1][j2]==fuzhuxian&&a[i3+1][j3]==fuzhuxian)
				{
					i++,i1++,i2++,i3++;
				}
				a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				return;
			}
			if(KEY_DOWN('S'))
			{
				yanshi=1;
			}
			else
			{
				yanshi=10;
			}
			if(d==1)
			{
				if(ysld==1)
				{
					int aaaa1=i,bbbb1=i1,cccc1=i2,dddd1=i3,aaaa2=j,bbbb2=j11,cccc2=j2,dddd2=j3;
					while(a[cccc1+1][cccc2]==fuzhuxian&&a[dddd1+1][dddd2]==fuzhuxian)
					{
						aaaa1++,bbbb1++,cccc1++,dddd1++;
					}
					mapp[aaaa1][aaaa2]=2,mapp[bbbb1][bbbb2]=2,mapp[cccc1][cccc2]=2,mapp[dddd1][dddd2]=2;
				}
				cou();
			}
		}
	}
}
void block3()
{
	if(i==2)
	{
		j=5,j11=6,j2=6,j3=7,panding=0;
		a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i2][j3]=fangkuai;
		_sleep(100);
	}
	while(1)
	{
		if(panding==0)
		{
			if(a[i+1][j]!=fuzhuxian||a[i2+1][j2]!=fuzhuxian||a[i3+1][j3]!=fuzhuxian)
			{
				break;
			}
			_sleep(100);
			a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
			i++,i1++,i2++,i3++;
			a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
		}
		if(panding==1)
		{
			if(a[i3+1][j3]!=fuzhuxian||a[i1+1][j11]!=fuzhuxian)
			{
				break;
			}
			_sleep(100);
			a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
			i++,i1++,i2++,i3++;
			a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
		}
		if(ysld==1)
		{
			int aaaa1=i,bbbb1=i1,cccc1=i2,dddd1=i3,aaaa2=j,bbbb2=j11,cccc2=j2,dddd2=j3;
			if(panding==1)
			{
				while(a[bbbb1+1][bbbb2]==fuzhuxian&&a[dddd1+1][dddd2]==fuzhuxian)
				{
					aaaa1++,bbbb1++,cccc1++,dddd1++;
				}
			}
			else
			{
				while(a[aaaa1+1][aaaa2]==fuzhuxian&&a[cccc1+1][cccc2]==fuzhuxian&&a[dddd1+1][dddd2]==fuzhuxian)
				{
					aaaa1++,bbbb1++,cccc1++,dddd1++;
				}
			}
			mapp[aaaa1][aaaa2]=3,mapp[bbbb1][bbbb2]=3,mapp[cccc1][cccc2]=3,mapp[dddd1][dddd2]=3;
		}
		cou();
		for(int ii=1;ii<=yanshi;ii++)
		{
			if(xz==2)
			{
				go();
				if(KEY_DOWN(VK_UP))
				{
					for(int kk=1;kk<=3;kk++)
					{
						if(a[iii-1][jjj]==fangkuai)
						{
							break;
						}
						iii--;
						a[iii+1][jjj]=' ';
						a[iii][jjj]='@';
						cou();
						go();
						_sleep(100);
						if(iii==nx&&jjj==ny)
						{
							system("color E");
							cout<<"nbnbnb gg";gg=1;
							_sleep(2000);
							SetColorAndBackground(7,0);
							return;
						}
					}
				}
				while(1)
				{
					if(a[iii+1][jjj]=='#')
					{
						break;
					}
					iii++;
					a[iii-1][jjj]=' ';
					a[iii][jjj]='@';
					cou();
					_sleep(100);
					go();
					if(iii==nx&&jjj==ny)
					{
						system("color E");
						cout<<"nbnbnb gg";gg=1;
						_sleep(2000);
						SetColorAndBackground(7,0);
						return;
					}
				}
			}
			d=0;
			_sleep(100);
			if(KEY_DOWN('A'))
			{
				d=1;
				if(panding==0&&a[i][j-1]!=fangkuai&&a[i2][j2-1]!=fangkuai)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
				  	j--,j11--,j2--,j3--;
				  	a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
				if(panding==1&&a[i2][j2-1]!=fangkuai&&a[i3][j3-1]!=fangkuai&&a[i][j-1]!=fangkuai)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
				  	j--,j11--,j2--,j3--;
				  	a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
			}
			if(KEY_DOWN('D'))
			{
				d=1;
				if(panding==0&&a[i1][j11+1]!=fangkuai&&a[i3][j3+1]!=fangkuai)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
				  	j++,j11++,j2++,j3++;
				  	a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
				if(panding==1&&a[i][j+1]!=fangkuai&&a[i1][j11+1]!=fangkuai&&a[i3][j3+1]!=fangkuai)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
				  	j++,j11++,j2++,j3++;
				  	a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
			}
			if(KEY_DOWN('W'))
			{
				d=1;
				panding++;
				if(panding==2)
				{
					if(panding==2&&a[i2][j2-1]!=fangkuai&&a[i1+1][j11]!=fangkuai)
					{
						a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
						i++,j-=2,j11--,i2++,j3++;
						a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
						panding=0;
					}
					else
					{
						panding=1;
					}
				}
				else
				{
					if(panding==1&&a[i3-1][j3]!=fangkuai&&a[i3-2][j3]!=fangkuai)
					{
						a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
						i--,j+=2,j11++,i2--,j3--;
						a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
					}
					else
					{
						panding=0;
					}
				}
			}
			if(KEY_DOWN('J'))
			{
				d=1;
				if(panding==0)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
					while(a[i+1][j]==fuzhuxian&&a[i2+1][j2]==fuzhuxian&&a[i3+1][j3]==fuzhuxian)
					{
						i++,i1++,i2++,i3++;
					}
					a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
				if(panding==1)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
					while(a[i3+1][j3]==fuzhuxian&&a[i1+1][j11]==fuzhuxian)
					{
						i++,i1++,i2++,i3++;
					}		
					a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
				return;
			}
			if(KEY_DOWN('S'))
			{
				yanshi=1;
			}
			else
			{
				yanshi=10;
			}
			if(d==1)
			{
				if(ysld==1)
				{
					int aaaa1=i,bbbb1=i1,cccc1=i2,dddd1=i3,aaaa2=j,bbbb2=j11,cccc2=j2,dddd2=j3;
					if(panding==1)
					{
						while(a[bbbb1+1][bbbb2]==fuzhuxian&&a[dddd1+1][dddd2]==fuzhuxian)
						{
							aaaa1++,bbbb1++,cccc1++,dddd1++;
						}
					}
					else
					{
						while(a[aaaa1+1][aaaa2]==fuzhuxian&&a[cccc1+1][cccc2]==fuzhuxian&&a[dddd1+1][dddd2]==fuzhuxian)
						{
							aaaa1++,bbbb1++,cccc1++,dddd1++;
						}
					}
					mapp[aaaa1][aaaa2]=3,mapp[bbbb1][bbbb2]=3,mapp[cccc1][cccc2]=3,mapp[dddd1][dddd2]=3;
				}
				cou();
			}
		}
	}
}
void block4()
{
	if(i==2)
	{
		j=7,j11=6,j2=6,j3=5,panding=0;
		a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
		_sleep(100);
	}
	while(1)
	{
		if(panding==0)
		{
			if(a[i+1][j]!=fuzhuxian||a[i2+1][j2]!=fuzhuxian||a[i3+1][j3]!=fuzhuxian)
			{
				break;
			}
			_sleep(100);
			a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
			i++,i1++,i2++,i3++;
			a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
		}
		if(panding==1)
		{
			if(a[i3+1][j3]!=fuzhuxian||a[i1+1][j11]!=fuzhuxian)
			{
				break;
			}
			_sleep(100);
			a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
			i++,i1++,i2++,i3++;
			a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
		}
		if(ysld==1)
		{
			int aaaa1=i,bbbb1=i1,cccc1=i2,dddd1=i3,aaaa2=j,bbbb2=j11,cccc2=j2,dddd2=j3;
			if(panding==1)
			{
				while(a[bbbb1+1][bbbb2]==fuzhuxian&&a[dddd1+1][dddd2]==fuzhuxian)
				{
					aaaa1++,bbbb1++,cccc1++,dddd1++;
				}
			}
			else
			{
				while(a[aaaa1+1][aaaa2]==fuzhuxian&&a[cccc1+1][cccc2]==fuzhuxian&&a[dddd1+1][dddd2]==fuzhuxian)
				{
					aaaa1++,bbbb1++,cccc1++,dddd1++;
				}
			}
			mapp[aaaa1][aaaa2]=4,mapp[bbbb1][bbbb2]=4,mapp[cccc1][cccc2]=4,mapp[dddd1][dddd2]=4;
		}
		cou();
		for(int ii=1;ii<=yanshi;ii++)
		{
			if(xz==2)
			{
				go();
				if(KEY_DOWN(VK_UP))
				{
					for(int kk=1;kk<=3;kk++)
					{
						if(a[iii-1][jjj]==fangkuai)
						{
							break;
						}
						iii--;
						a[iii+1][jjj]=' ';
						a[iii][jjj]='@';
						cou();
						go();
						_sleep(100);
						if(iii==nx&&jjj==ny)
						{
							system("color E");
							cout<<"nbnbnb gg";gg=1;
							_sleep(2000);
							SetColorAndBackground(7,0);
							return;
						}
					}
				}
				while(1)
				{
					if(a[iii+1][jjj]=='#')
					{
						break;
					}
					iii++;
					a[iii-1][jjj]=' ';
					a[iii][jjj]='@';
					cou();
					_sleep(100);
					go();
					if(iii==nx&&jjj==ny)
					{
						system("color E");
						cout<<"nbnbnb gg";gg=1;
						_sleep(2000);
						SetColorAndBackground(7,0);
						return;
					}
				}
			}
			d=0;
			_sleep(100);
			if(KEY_DOWN('A'))
			{
				d=1;
				if(panding==0&&a[i1][j11-1]!=fangkuai&&a[i3][j3-1]!=fangkuai)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
				  	j--,j11--,j2--,j3--;
				  	a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
				if(panding==1&&a[i1][j11-1]!=fangkuai&&a[i3][j3-1]!=fangkuai&&a[i][j-1]!=fangkuai)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
				  	j--,j11--,j2--,j3--;
				  	a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
			}
			if(KEY_DOWN('D'))
			{
				d=1;
				if(panding==0&&a[i2][j2+1]!=fangkuai&&a[i][j+1]!=fangkuai)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
				  	j++,j11++,j2++,j3++;
				  	a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
				if(panding==1&&a[i][j+1]!=fangkuai&&a[i2][j2+1]!=fangkuai&&a[i3][j3+1]!=fangkuai)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
				  	j++,j11++,j2++,j3++;
				  	a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
			}
			if(KEY_DOWN('W'))
			{
				d=1;
				panding++;
				if(panding==2)
				{
					if(a[i2][j2+1]!=fangkuai&&a[i1+1][j11]!=fangkuai)
					{
						a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
						i++,j+=2,j11++,i2++,j3--;
						a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
						panding=0;
					}
					else
					{
						panding=1; 
					}
				}
				else
				{
					if(panding==1&&a[i3-1][j3]!=fangkuai&&a[i3-2][j3]!=fangkuai)
					{
						a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
						i--,j-=2,j11--,i2--,j3++;
						a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
					}
					else
					{
						panding=0;
					}
				}
			}
			if(KEY_DOWN('J'))
			{
				d=1;
				if(panding==0)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
					while(a[i+1][j]==fuzhuxian&&a[i2+1][j2]==fuzhuxian&&a[i3+1][j3]==fuzhuxian)
					{
						i++,i1++,i2++,i3++;
					}
					a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
				if(panding==1)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
					while(a[i3+1][j3]==fuzhuxian&&a[i1+1][j11]==fuzhuxian)
					{
						i++,i1++,i2++,i3++;
					}		
					a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
				return;
			}
			if(KEY_DOWN('S'))
			{
				yanshi=1;
			}
			else
			{
				yanshi=10;
			}
			if(d==1)
			{
				if(ysld==1)
				{
					int aaaa1=i,bbbb1=i1,cccc1=i2,dddd1=i3,aaaa2=j,bbbb2=j11,cccc2=j2,dddd2=j3;
					if(panding==1)
					{
						while(a[bbbb1+1][bbbb2]==fuzhuxian&&a[dddd1+1][dddd2]==fuzhuxian)
						{
							aaaa1++,bbbb1++,cccc1++,dddd1++;
						}
					}
					else
					{
						while(a[aaaa1+1][aaaa2]==fuzhuxian&&a[cccc1+1][cccc2]==fuzhuxian&&a[dddd1+1][dddd2]==fuzhuxian)
						{
							aaaa1++,bbbb1++,cccc1++,dddd1++;
						}
					}
					mapp[aaaa1][aaaa2]=4,mapp[bbbb1][bbbb2]=4,mapp[cccc1][cccc2]=4,mapp[dddd1][dddd2]=4;
				}
				cou();
			}
		}
	}
}
void block5()
{
	if(i==2)
	{
		j=6,j11=5,j2=6,j3=7,panding=0;
		a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
		_sleep(100);
	}
	while(1)
	{
		if(panding==0)
		{
			if(a[i1+1][j11]!=fuzhuxian||a[i2+1][j2]!=fuzhuxian||a[i3+1][j3]!=fuzhuxian)
			{
				break;
			}
			_sleep(100);
			a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
			i++,i1++,i2++,i3++;
			a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
		}
		if(panding==1)
		{
			if(a[i3+1][j3]!=fuzhuxian||a[i2+1][j2]!=fuzhuxian)
			{
				break;
			}
			_sleep(100);
			a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
			i++,i1++,i2++,i3++;
			a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
		}
		if(panding==2)
		{
			if(a[i3+1][j3]!=fuzhuxian||a[i2+1][j2]!=fuzhuxian||a[i+1][j]!=fuzhuxian)
			{
				break;
			}
			_sleep(100);
			a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
			i++,i1++,i2++,i3++;
			a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
		}
		if(panding==3)
		{
			if(a[i3+1][j3]!=fuzhuxian||a[i+1][j]!=fuzhuxian)
			{
				break;
			}
			_sleep(100);
			a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
			i++,i1++,i2++,i3++;
			a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
		}
		if(ysld==1)
		{
			int aaaa1=i,bbbb1=i1,cccc1=i2,dddd1=i3,aaaa2=j,bbbb2=j11,cccc2=j2,dddd2=j3;
			if(panding==0)
			{
				while(a[bbbb1+1][bbbb2]==fuzhuxian&&a[cccc1+1][cccc2]==fuzhuxian&&a[dddd1+1][dddd2]==fuzhuxian)
				{
					aaaa1++,bbbb1++,cccc1++,dddd1++;
				}
			}
			if(panding==1)
			{
				while(a[cccc1+1][cccc2]==fuzhuxian&&a[dddd1+1][dddd2]==fuzhuxian)
				{
					aaaa1++,bbbb1++,cccc1++,dddd1++;
				}
			}
			if(panding==2)
			{
				while(a[aaaa1+1][aaaa2]==fuzhuxian&&a[cccc1+1][cccc2]==fuzhuxian&&a[dddd1+1][dddd2]==fuzhuxian)
				{
					aaaa1++,bbbb1++,cccc1++,dddd1++;
				}
			}
			if(panding==3)
			{
				while(a[aaaa1+1][aaaa2]==fuzhuxian&&a[dddd1+1][dddd2]==fuzhuxian)
				{
					aaaa1++,bbbb1++,cccc1++,dddd1++;
				}
			}
			mapp[aaaa1][aaaa2]=5,mapp[bbbb1][bbbb2]=5,mapp[cccc1][cccc2]=5,mapp[dddd1][dddd2]=5;
		}
		cou();
		for(int ii=1;ii<=yanshi;ii++)
		{
			if(xz==2)
			{
				go();
				if(KEY_DOWN(VK_UP))
				{
					for(int kk=1;kk<=3;kk++)
					{
						if(a[iii-1][jjj]==fangkuai)
						{
							break;
						}
						iii--;
						a[iii+1][jjj]=' ';
						a[iii][jjj]='@';
						cou();
						go();
						_sleep(100);
						if(iii==nx&&jjj==ny)
						{
							system("color E");
							cout<<"nbnbnb gg";gg=1;
							_sleep(2000);
							SetColorAndBackground(7,0);
							return;
						}
					}
				}
				while(1)
				{
					if(a[iii+1][jjj]=='#')
					{
						break;
					}
					iii++;
					a[iii-1][jjj]=' ';
					a[iii][jjj]='@';
					cou();
					_sleep(100);
					go();
					if(iii==nx&&jjj==ny)
					{
						system("color E");
						cout<<"nbnbnb gg";gg=1;
						_sleep(2000);
						SetColorAndBackground(7,0);
						return;
					}
				}
			}
			d=0;
			_sleep(100);
			if(KEY_DOWN('A'))
			{
				d=1;
				if(panding==0&&a[i1][j11-1]!=fangkuai&&a[i][j-1]!=fangkuai)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
				  	j--,j11--,j2--,j3--;
				  	a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
				if(panding==1&&a[i1][j11-1]!=fangkuai&&a[i2][j2-1]!=fangkuai&&a[i][j-1]!=fangkuai)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
				  	j--,j11--,j2--,j3--;
				  	a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
				if(panding==2&&a[i3][j3-1]!=fangkuai&&a[i][j-1]!=fangkuai)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
				  	j--,j11--,j2--,j3--;
				  	a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
				if(panding==3&&a[i1][j11-1]!=fangkuai&&a[i3][j3-1]!=fangkuai&&a[i][j-1]!=fangkuai)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
				  	j--,j11--,j2--,j3--;
				  	a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
			}
			if(KEY_DOWN('D'))
			{
				d=1;
				if(panding==0&&a[i3][j3+1]!=fangkuai&&a[i][j+1]!=fangkuai)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
				  	j++,j11++,j2++,j3++;
				  	a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
				if(panding==1&&a[i][j+1]!=fangkuai&&a[i2][j2+1]!=fangkuai&&a[i3][j3+1]!=fangkuai)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
				  	j++,j11++,j2++,j3++;
				  	a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
				if(panding==2&&a[i3][j3+1]!=fangkuai&&a[i2][j2+1]!=fangkuai)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
				  	j++,j11++,j2++,j3++;
				  	a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
				if(panding==3&&a[i1][j11+1]!=fangkuai&&a[i2][j2+1]!=fangkuai&&a[i3][j3+1]!=fangkuai)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
				  	j++,j11++,j2++,j3++;
				  	a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
			}
			if(KEY_DOWN('W'))
			{
				d=1;
				panding++;
				switch(panding)
				{
					case 4:	if(a[i2][j2+1]!=fangkuai)
							{
								a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
								i--,j++,j11--,i1++,i3--,j3++;
								a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
								panding=0;
							}
							else
							{
								panding=3; 
							}
							break;
					case 1: if(a[i2+1][j2]!=fangkuai)
							{
								a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
								j11++,i2++;
								a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
							}
							else
							{
								panding=0;
							}
							break;
					case 2: if(a[i1][j11-1]!=fangkuai)
							{
								a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
								i++,j--,i2--,j2++,i3++,j3--;
								a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
							}
							else
							{
								panding=1;
							}
							break;
					case 3: if(a[i1-1][j11]!=fangkuai)
							{
								a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
								i1--,j2--;
								a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
							}
							else
							{
								panding=2;
							}
							break;
				}
			}
			if(KEY_DOWN('J'))
			{
				d=1;
				if(panding==0)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
					while(a[i1+1][j11]==fuzhuxian&&a[i2+1][j2]==fuzhuxian&&a[i3+1][j3]==fuzhuxian)
					{
						i++,i1++,i2++,i3++;
					}
					a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
				if(panding==1)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
					while(a[i3+1][j3]==fuzhuxian&&a[i2+1][j2]==fuzhuxian)
					{
						i++,i1++,i2++,i3++;
					}		
					a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
				if(panding==2)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
					while(a[i+1][j]==fuzhuxian&&a[i2+1][j2]==fuzhuxian&&a[i3+1][j3]==fuzhuxian)
					{
						i++,i1++,i2++,i3++;
					}
					a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
				if(panding==3)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
					while(a[i3+1][j3]==fuzhuxian&&a[i+1][j]==fuzhuxian)
					{
						i++,i1++,i2++,i3++;
					}		
					a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
				return;
			}
			if(KEY_DOWN('S'))
			{
				yanshi=1;
			}
			else
			{
				yanshi=10;
			}
			if(d==1)
			{
				if(ysld==1)
				{
					int aaaa1=i,bbbb1=i1,cccc1=i2,dddd1=i3,aaaa2=j,bbbb2=j11,cccc2=j2,dddd2=j3;
					if(panding==0)
					{
						while(a[bbbb1+1][bbbb2]==fuzhuxian&&a[cccc1+1][cccc2]==fuzhuxian&&a[dddd1+1][dddd2]==fuzhuxian)
						{
							aaaa1++,bbbb1++,cccc1++,dddd1++;
						}
					}
					if(panding==1)
					{
						while(a[cccc1+1][cccc2]==fuzhuxian&&a[dddd1+1][dddd2]==fuzhuxian)
						{
							aaaa1++,bbbb1++,cccc1++,dddd1++;
						}
					}
					if(panding==2)
					{
						while(a[aaaa1+1][aaaa2]==fuzhuxian&&a[cccc1+1][cccc2]==fuzhuxian&&a[dddd1+1][dddd2]==fuzhuxian)
						{
							aaaa1++,bbbb1++,cccc1++,dddd1++;
						}
					}
					if(panding==3)
					{
						while(a[aaaa1+1][aaaa2]==fuzhuxian&&a[dddd1+1][dddd2]==fuzhuxian)
						{
							aaaa1++,bbbb1++,cccc1++,dddd1++;
						}
					}
					mapp[aaaa1][aaaa2]=5,mapp[bbbb1][bbbb2]=5,mapp[cccc1][cccc2]=5,mapp[dddd1][dddd2]=5;
				}
				cou();
			}
		}
	}
}
void block6()
{
	if(i==2)
	{
		j=7,j11=5,j2=6,j3=7,panding=0;
		a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
		_sleep(100);
	}
	while(1)
	{
		if(panding==0)
		{
			if(a[i1+1][j11]!=fuzhuxian||a[i2+1][j2]!=fuzhuxian||a[i3+1][j3]!=fuzhuxian)
			{
				break;
			}
			_sleep(100);
			a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
			i++,i1++,i2++,i3++;
			a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
		}
		if(panding==1)
		{
			if(a[i3+1][j3]!=fuzhuxian||a[i2+1][j2]!=fuzhuxian)
			{
				break;
			}
			_sleep(100);
			a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
			i++,i1++,i2++,i3++;
			a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
		}
		if(panding==2)
		{
			if(a[i3+1][j3]!=fuzhuxian||a[i2+1][j2]!=fuzhuxian||a[i1+1][j11]!=fuzhuxian)
			{
				break;
			}
			_sleep(100);
			a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
			i++,i1++,i2++,i3++;
			a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
		}
		if(panding==3)
		{
			if(a[i3+1][j3]!=fuzhuxian||a[i+1][j]!=fuzhuxian)
			{
				break;
			}
			_sleep(100);
			a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
			i++,i1++,i2++,i3++;
			a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
		}
		if(ysld==1)
		{
			int aaaa1=i,bbbb1=i1,cccc1=i2,dddd1=i3,aaaa2=j,bbbb2=j11,cccc2=j2,dddd2=j3;
			if(panding==0)
			{
				while(a[bbbb1+1][bbbb2]==fuzhuxian&&a[cccc1+1][cccc2]==fuzhuxian&&a[dddd1+1][dddd2]==fuzhuxian)
				{
					aaaa1++,bbbb1++,cccc1++,dddd1++;
				}
			}
			if(panding==1)
			{
				while(a[cccc1+1][cccc2]==fuzhuxian&&a[dddd1+1][dddd2]==fuzhuxian)
				{
					aaaa1++,bbbb1++,cccc1++,dddd1++;
				}
			}
			if(panding==2)
			{
				while(a[bbbb1+1][bbbb2]==fuzhuxian&&a[cccc1+1][cccc2]==fuzhuxian&&a[dddd1+1][dddd2]==fuzhuxian)
				{
					aaaa1++,bbbb1++,cccc1++,dddd1++;
				}
			}
			if(panding==3)
			{
				while(a[aaaa1+1][aaaa2]==fuzhuxian&&a[dddd1+1][dddd2]==fuzhuxian)
				{
					aaaa1++,bbbb1++,cccc1++,dddd1++;
				}
			}
			mapp[aaaa1][aaaa2]=6,mapp[bbbb1][bbbb2]=6,mapp[cccc1][cccc2]=6,mapp[dddd1][dddd2]=6;
		}
		cou();
		for(int ii=1;ii<=yanshi;ii++)
		{
			if(xz==2)
			{
				go();
				if(KEY_DOWN(VK_UP))
				{
					for(int kk=1;kk<=3;kk++)
					{
						if(a[iii-1][jjj]==fangkuai)
						{
							break;
						}
						iii--;
						a[iii+1][jjj]=' ';
						a[iii][jjj]='@';
						cou();
						go();
						_sleep(100);
						if(iii==nx&&jjj==ny)
						{
							system("color E");
							cout<<"nbnbnb gg";gg=1;
							_sleep(2000);
							SetColorAndBackground(7,0);
							return;
						}
					}
				}
				while(1)
				{
					if(a[iii+1][jjj]=='#')
					{
						break;
					}
					iii++;
					a[iii-1][jjj]=' ';
					a[iii][jjj]='@';
					cou();
					_sleep(100);
					go();
					if(iii==nx&&jjj==ny)
					{
						system("color E");
						cout<<"nbnbnb gg";gg=1;
						_sleep(2000);
						SetColorAndBackground(7,0);
						return;
					}
				}
			}
			d=0;
			_sleep(100);
			if(KEY_DOWN('A'))
			{
				d=1;
				if(panding==0&&a[i1][j11-1]!=fangkuai&&a[i][j-1]!=fangkuai)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
				  	j--,j11--,j2--,j3--;
				  	a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
				if(panding==1&&a[i1][j11-1]!=fangkuai&&a[i2][j2-1]!=fangkuai&&a[i][j-1]!=fangkuai)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
				  	j--,j11--,j2--,j3--;
				  	a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
				if(panding==2&&a[i3][j3-1]!=fangkuai&&a[i][j-1]!=fangkuai)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
				  	j--,j11--,j2--,j3--;
				  	a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
				if(panding==3&&a[i2][j2-1]!=fangkuai&&a[i3][j3-1]!=fangkuai&&a[i][j-1]!=fangkuai)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
				  	j--,j11--,j2--,j3--;
				  	a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
			}
			if(KEY_DOWN('D'))
			{
				d=1;
				if(panding==0&&a[i3][j3+1]!=fangkuai&&a[i][j+1]!=fangkuai)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
				  	j++,j11++,j2++,j3++;
				  	a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
				if(panding==1&&a[i][j+1]!=fangkuai&&a[i1][j11+1]!=fangkuai&&a[i3][j3+1]!=fangkuai)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
				  	j++,j11++,j2++,j3++;
				  	a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
				if(panding==2&&a[i3][j3+1]!=fangkuai&&a[i2][j2+1]!=fangkuai)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
				  	j++,j11++,j2++,j3++;
				  	a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
				if(panding==3&&a[i1][j11+1]!=fangkuai&&a[i2][j2+1]!=fangkuai&&a[i3][j3+1]!=fangkuai)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
				  	j++,j11++,j2++,j3++;
				  	a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
			}
			if(KEY_DOWN('W'))
			{
				d=1;
				panding++;
				switch(panding)
				{
					case 4:	if(a[i2][j2-1]!=fangkuai&&a[i2][j2-2]!=fangkuai)
							{
								a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
								j++,j11-=2,i1++,j2--,i3--;
								a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
								panding=0;
							}
							else
							{
								panding=3; 
							}
							break;
					case 1: if(a[i2-1][j2]!=fangkuai&&a[i2-2][j2]!=fangkuai)
							{
								a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
								j11++,i1--,i--,j--;
								a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
							}
							else
							{
								panding=0;
							}
							break;
					case 2: if(a[i1][j11+1]!=fangkuai&&a[i1][j11+2]!=fangkuai)
							{
								a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
								j11++,j3--,i++,i2--,j2+=2;
								a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
							}
							else
							{
								panding=1; 
							}
							break;
					case 3: if(a[i1-1][j11]!=fangkuai&&a[i-1][j]!=fangkuai&&a[i1+1][j11]!=fangkuai)
							{
								a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
								i--,i1--,j3++,j2--;
								a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
							}
							else
							{
								panding=2;
							}
							break;
				}
			}
			if(KEY_DOWN('J'))
			{
				d=1;
				if(panding==0)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
					while(a[i1+1][j11]==fuzhuxian&&a[i2+1][j2]==fuzhuxian&&a[i3+1][j3]==fuzhuxian)
					{
						i++,i1++,i2++,i3++;
					}
					a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
				if(panding==1)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
					while(a[i3+1][j3]==fuzhuxian&&a[i2+1][j2]==fuzhuxian)
					{
						i++,i1++,i2++,i3++;
					}		
					a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
				if(panding==2)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
					while(a[i1+1][j11]==fuzhuxian&&a[i2+1][j2]==fuzhuxian&&a[i3+1][j3]==fuzhuxian)
					{
						i++,i1++,i2++,i3++;
					}
					a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
				if(panding==3)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
					while(a[i3+1][j3]==fuzhuxian&&a[i+1][j]==fuzhuxian)
					{
						i++,i1++,i2++,i3++;
					}		
					a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
				return;
			}
			if(KEY_DOWN('S'))
			{
				yanshi=1;
			}
			else
			{
				yanshi=10;
			}
			if(d==1)
			{
				if(ysld==1)
				{
					int aaaa1=i,bbbb1=i1,cccc1=i2,dddd1=i3,aaaa2=j,bbbb2=j11,cccc2=j2,dddd2=j3;
					if(panding==0)
					{
						while(a[bbbb1+1][bbbb2]==fuzhuxian&&a[cccc1+1][cccc2]==fuzhuxian&&a[dddd1+1][dddd2]==fuzhuxian)
						{
							aaaa1++,bbbb1++,cccc1++,dddd1++;
						}
					}
					if(panding==1)
					{
						while(a[cccc1+1][cccc2]==fuzhuxian&&a[dddd1+1][dddd2]==fuzhuxian)
						{
							aaaa1++,bbbb1++,cccc1++,dddd1++;
						}
					}
					if(panding==2)
					{
						while(a[bbbb1+1][bbbb2]==fuzhuxian&&a[cccc1+1][cccc2]==fuzhuxian&&a[dddd1+1][dddd2]==fuzhuxian)
						{
							aaaa1++,bbbb1++,cccc1++,dddd1++;
						}
					}
					if(panding==3)
					{
						while(a[aaaa1+1][aaaa2]==fuzhuxian&&a[dddd1+1][dddd2]==fuzhuxian)
						{
							aaaa1++,bbbb1++,cccc1++,dddd1++;
						}
					}
					mapp[aaaa1][aaaa2]=6,mapp[bbbb1][bbbb2]=6,mapp[cccc1][cccc2]=6,mapp[dddd1][dddd2]=6;
				}
				cou();
			}
		}
	}
}
void block7()
{
	if(i==2)
	{
		j=5,j11=5,j2=6,j3=7,panding=0;
		a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
		_sleep(100);
	}
	while(1)
	{
		if(panding==0)
		{
			if(a[i1+1][j11]!=fuzhuxian||a[i2+1][j2]!=fuzhuxian||a[i3+1][j3]!=fuzhuxian)
			{
				break;
			}
			_sleep(100);
			a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
			i++,i1++,i2++,i3++;
			a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
		}
		if(panding==1)
		{
			if(a[i3+1][j3]!=fuzhuxian||a[i1+1][j11]!=fuzhuxian)
			{
				break;
			}
			_sleep(100);
			a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
			i++,i1++,i2++,i3++;
			a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
		}
		if(panding==2)
		{
			if(a[i3+1][j3]!=fuzhuxian||a[i1+1][j11]!=fuzhuxian||a[i+1][j]!=fuzhuxian)
			{
				break;
			}
			_sleep(100);
			a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
			i++,i1++,i2++,i3++;
			a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
		}
		if(panding==3)
		{
			if(a[i3+1][j3]!=fuzhuxian||a[i2+1][j2]!=fuzhuxian)
			{
				break;
			}
			_sleep(100);
			a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
			i++,i1++,i2++,i3++;
			a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
		}
		if(ysld==1)
		{
			int aaaa1=i,bbbb1=i1,cccc1=i2,dddd1=i3,aaaa2=j,bbbb2=j11,cccc2=j2,dddd2=j3;
			if(panding==0)
			{
				while(a[bbbb1+1][bbbb2]==fuzhuxian&&a[cccc1+1][cccc2]==fuzhuxian&&a[dddd1+1][dddd2]==fuzhuxian)
				{
					aaaa1++,bbbb1++,cccc1++,dddd1++;
				}
			}
			if(panding==1)
			{
				while(a[bbbb1+1][bbbb2]==fuzhuxian&&a[dddd1+1][dddd2]==fuzhuxian)
				{
					aaaa1++,bbbb1++,cccc1++,dddd1++;
				}
			}
			if(panding==2)
			{
				while(a[bbbb1+1][bbbb2]==fuzhuxian&&a[aaaa1+1][aaaa2]==fuzhuxian&&a[dddd1+1][dddd2]==fuzhuxian)
				{
					aaaa1++,bbbb1++,cccc1++,dddd1++;
				}
			}
			if(panding==3)
			{
				while(a[cccc1+1][cccc2]==fuzhuxian&&a[dddd1+1][dddd2]==fuzhuxian)
				{
					aaaa1++,bbbb1++,cccc1++,dddd1++;
				}
			}
			mapp[aaaa1][aaaa2]=7,mapp[bbbb1][bbbb2]=7,mapp[cccc1][cccc2]=7,mapp[dddd1][dddd2]=7;
		}
		cou();
		for(int ii=1;ii<=yanshi;ii++)
		{
			if(xz==2)
			{
				go();
				if(KEY_DOWN(VK_UP))
				{
					for(int kk=1;kk<=3;kk++)
					{
						if(a[iii-1][jjj]==fangkuai)
						{
							break;
						}
						iii--;
						a[iii+1][jjj]=' ';
						a[iii][jjj]='@';
						cou();
						go();
						_sleep(100);
						if(iii==nx&&jjj==ny)
						{
							system("color E");
							cout<<"nbnbnb gg";gg=1;
							_sleep(2000);
							SetColorAndBackground(7,0);
							return;
						}
					}
				}
				while(1)
				{
					if(a[iii+1][jjj]=='#')
					{
						break;
					}
					iii++;
					a[iii-1][jjj]=' ';
					a[iii][jjj]='@';
					cou();
					_sleep(100);
					go();
					if(iii==nx&&jjj==ny)
					{
						system("color E");
						cout<<"nbnbnb gg";gg=1;
						_sleep(2000);
						SetColorAndBackground(7,0);
						return;
					}
				}
			}
			d=0;
			_sleep(100);
			if(KEY_DOWN('A'))
			{
				d=1;
				if(panding==0&&a[i1][j11-1]!=fangkuai&&a[i][j-1]!=fangkuai)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
				  	j--,j11--,j2--,j3--;
				  	a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
				if(panding==1&&a[i3][j3-1]!=fangkuai&&a[i2][j2-1]!=fangkuai&&a[i][j-1]!=fangkuai)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
				  	j--,j11--,j2--,j3--;
				  	a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
				if(panding==2&&a[i3][j3-1]!=fangkuai&&a[i][j-1]!=fangkuai)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
				  	j--,j11--,j2--,j3--;
				  	a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
				if(panding==3&&a[i2][j2-1]!=fangkuai&&a[i1][j11-1]!=fangkuai&&a[i][j-1]!=fangkuai)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
				  	j--,j11--,j2--,j3--;
				  	a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
			}
			if(KEY_DOWN('D'))
			{
				d=1;
				if(panding==0&&a[i3][j3+1]!=fangkuai&&a[i][j+1]!=fangkuai)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
				  	j++,j11++,j2++,j3++;
				  	a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
				if(panding==1&&a[i3][j3+1]!=fangkuai&&a[i1][j11+1]!=fangkuai&&a[i2][j2+1]!=fangkuai)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
				  	j++,j11++,j2++,j3++;
				  	a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
				if(panding==2&&a[i3][j3+1]!=fangkuai&&a[i2][j2+1]!=fangkuai)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
				  	j++,j11++,j2++,j3++;
				  	a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
				if(panding==3&&a[i1][j11+1]!=fangkuai&&a[i1][j11+1]!=fangkuai&&a[i3][j3+1]!=fangkuai)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
				  	j++,j11++,j2++,j3++;
				  	a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
			}
			if(KEY_DOWN('W'))
			{
				d=1;
				panding++;
				switch(panding)
				{
					case 4:	if(a[i2][j2+2]!=fangkuai)
							{
								a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
								i++,j--,j11--,i1++,j2++,j3++;
								a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
								panding=0;
							}
							else
							{
								panding=3;
							}
							break;
					case 1: if(a[i][j+1]!=fangkuai&&a[i1+1][j11]!=fangkuai)
							{
								a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
								j11++,i1--,j2--,i3++,j3-=2;
								a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
							}
							else
							{
								panding=0;
							}
							break;
					case 2: if(a[i1][j11+1]!=fangkuai&&a[i1+1][j11+1]!=fangkuai)
							{
								a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
								j3+=2,i3--,i2--,j2+=2;
								a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
							}
							else
							{
								panding=1; 
							}
							break;
					case 3: if(a[i1+1][j11]!=fangkuai&&a[i2-1][j2]!=fangkuai)
							{
								a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
								i--,j+=2,j11++,j2--,i2++;
								a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
							}
							else
							{
								panding=2;
							}
							break;
				}
			}
			if(KEY_DOWN('J'))
			{
				d=1;
				if(panding==0)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
					while(a[i1+1][j11]==fuzhuxian&&a[i2+1][j2]==fuzhuxian&&a[i3+1][j3]==fuzhuxian)
					{
						i++,i1++,i2++,i3++;
					}
					a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
				if(panding==1)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
					while(a[i3+1][j3]==fuzhuxian&&a[i1+1][j11]==fuzhuxian)
					{
						i++,i1++,i2++,i3++;
					}		
					a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
				if(panding==2)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
					while(a[i1+1][j11]==fuzhuxian&&a[i+1][j]==fuzhuxian&&a[i3+1][j3]==fuzhuxian)
					{
						i++,i1++,i2++,i3++;
					}
					a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
				if(panding==3)
				{
					a[i][j]=fuzhuxian,a[i1][j11]=fuzhuxian,a[i2][j2]=fuzhuxian,a[i3][j3]=fuzhuxian;
					while(a[i3+1][j3]==fuzhuxian&&a[i2+1][j2]==fuzhuxian)
					{
						i++,i1++,i2++,i3++;
					}		
					a[i][j]=fangkuai,a[i1][j11]=fangkuai,a[i2][j2]=fangkuai,a[i3][j3]=fangkuai;
				}
				return;
			}
			if(KEY_DOWN('S'))
			{
				yanshi=1;
			}
			else
			{
				yanshi=10;
			}
			if(d==1)
			{
				if(ysld==1)
				{
					int aaaa1=i,bbbb1=i1,cccc1=i2,dddd1=i3,aaaa2=j,bbbb2=j11,cccc2=j2,dddd2=j3;
					if(panding==0)
					{
						while(a[bbbb1+1][bbbb2]==fuzhuxian&&a[cccc1+1][cccc2]==fuzhuxian&&a[dddd1+1][dddd2]==fuzhuxian)
						{
							aaaa1++,bbbb1++,cccc1++,dddd1++;
						}
					}
					if(panding==1)
					{
						while(a[bbbb1+1][bbbb2]==fuzhuxian&&a[dddd1+1][dddd2]==fuzhuxian)
						{
							aaaa1++,bbbb1++,cccc1++,dddd1++;
						}
					}
					if(panding==2)
					{
						while(a[bbbb1+1][bbbb2]==fuzhuxian&&a[aaaa1+1][aaaa2]==fuzhuxian&&a[dddd1+1][dddd2]==fuzhuxian)
						{
							aaaa1++,bbbb1++,cccc1++,dddd1++;
						}
					}
					if(panding==3)
					{
						while(a[cccc1+1][cccc2]==fuzhuxian&&a[dddd1+1][dddd2]==fuzhuxian)
						{
							aaaa1++,bbbb1++,cccc1++,dddd1++;
						}
					}
					mapp[aaaa1][aaaa2]=7,mapp[bbbb1][bbbb2]=7,mapp[cccc1][cccc2]=7,mapp[dddd1][dddd2]=7;
				}
				cou();
			}
		}
	}
}
int main()
{
	for(int ii=1;ii<=22;ii++)
	{
		for(int jj=1;jj<=19;jj++)
		{
			if(jj==1||jj==12||ii==1||ii==22||jj==19)
				a[ii][jj]=fangkuai;
			else
				a[ii][jj]=fuzhuxian;
		}
	}
	while(1)
	{
		xz=0;
		if(UI==1)
		{
			system("cls");
			UI=0;
			cout<<"     俄罗斯方块"<<endl<<endl<<"     1 经典模式"<<endl<<endl<<"     2 双人配合"<<endl<<endl<<"     Z 作者简介"<<endl<<endl<<"      S 设置";
		}
		if(KEY_DOWN('1')||KEY_DOWN('2'))
		{
			if(KEY_DOWN('1')||xz==1)
			{
				xz=1;
			}
			if(KEY_DOWN('2')||xz==2)
			{
				xz=2;
				iii=21,jjj=5;
				a[21][5]='@';
				srand((unsigned int)time(NULL));
				nx=rand()%(8-4+1)+4;
				srand((unsigned int)time(NULL));
				ny=rand()%(11-2+1)+2;
				a[nx][ny]=' ';
				mapp[nx][ny]=123;
			}
			srand((unsigned int)time(NULL));
			suiji2=rand()%7+1;
			srand((unsigned int)time(NULL));
			suiji1=rand()%7+1;
			while(1)
			{
				suiji=suiji1;
				suiji1=suiji2;
				srand((unsigned int)time(NULL));
				suiji2=rand()%7+1;
				yanshi=10;
				if(suiji==1)//长条 
				{
					i=3,i1=3,i2=3,i3=3,panding=0;
					block1();
					mapp[i][j]=1,mapp[i1][j11]=1,mapp[i2][j2]=1,mapp[i3][j3]=1;
				}
				if(suiji==2)//方四 
				{
					i=2,i1=2,i2=3,i3=3;
					block2();
					mapp[i][j]=2,mapp[i1][j11]=2,mapp[i2][j2]=2,mapp[i3][j3]=2;
				}
				if(suiji==3)//闪电左 
				{
					i=2,i1=2,i2=3,i3=3;
					block3();
					mapp[i][j]=3,mapp[i1][j11]=3,mapp[i2][j2]=3,mapp[i3][j3]=3;
				}
				if(suiji==4)//闪电右 
				{
					i=2,i1=2,i2=3,i3=3;
					block4();
					mapp[i][j]=4,mapp[i1][j11]=4,mapp[i2][j2]=4,mapp[i3][j3]=4;
				}
				if(suiji==5)//突突突 
				{
					i=2,i1=3,i2=3,i3=3,panding=0;
					block5();
					mapp[i][j]=5,mapp[i1][j11]=5,mapp[i2][j2]=5,mapp[i3][j3]=5;
				}
				if(suiji==6)//右钩 
				{
					i=2,i1=3,i2=3,i3=3,panding=0;
					block6();
					mapp[i][j]=6,mapp[i1][j11]=6,mapp[i2][j2]=6,mapp[i3][j3]=6;
				}
				if(suiji==7)//左钩 
				{
					i=2,i1=3,i2=3,i3=3,panding=0;
					block7();
					mapp[i][j]=7,mapp[i1][j11]=7,mapp[i2][j2]=7,mapp[i3][j3]=7;
				}
				if(maxfs<fs)
				{
					maxfs=fs;
				}
				if(gg==1)
				{
					gg=0;
					for(int ii=2;ii<=21;ii++)
					{
						for(int jj=2;jj<=11;jj++)
						{
							a[ii][jj]=' ';
							mapp[ii][jj]=0;
						}
					}
					UI=1;
					fs=0;
					break;
				}
				if(a[2][5]==fangkuai||a[2][6]==fangkuai)
				{
					qingping(0,0);
					for(int ii=1;ii<=22;ii++)
					{
						SetColorAndBackground(7,15);
						for(int jj=1;jj<=19;jj++)
						{
							SetColorAndBackground(7,15);
							if(mapp[ii][jj]==1)
							{
								SetColorAndBackground(3,15);
							}
							if(mapp[ii][jj]==2)
							{
								SetColorAndBackground(6,15);
							}
							if(mapp[ii][jj]==3)
							{
								SetColorAndBackground(2,15);
							}
							if(mapp[ii][jj]==4)
							{
								SetColorAndBackground(4,15);
							}
							if(mapp[ii][jj]==5)
							{
								SetColorAndBackground(5,15);
							}
							if(mapp[ii][jj]==6)
							{
								SetColorAndBackground(1,15);
							}
							if(mapp[ii][jj]==7)
							{
								SetColorAndBackground(12,15);
							}
							if(ii==11&&jj==5)
							{
								SetColorAndBackground(3,15);
								cout<<"game  over";
								SetColorAndBackground(7,15);
								jj=14;
								continue;
							}
							cout<<a[ii][jj];
						}
						cout<<endl;
					}
					_sleep(2000);
					gameover=1;
					for(int ii=2;ii<=21;ii++)
					{
						for(int jj=2;jj<=11;jj++)
						{
							a[ii][jj]=' ';
							mapp[ii][jj]=0;
						}
					}
					fs=0;
					SetColorAndBackground(7,0);
					system("pause >nul");
					if(gameover=1)
					{
						gameover=0;
						UI=1;
						break;
					}
				}
				for(int ii=2;ii<=21;ii++)
				{
					int ds=0;
					for(int jj=2;jj<=11;jj++)
					{
						if(a[ii][jj]==fuzhuxian)
						{
							ds=1;
							break;
						}
					}
					if(ds==0)
					{
						fs=fs+10;
						for(int jj=2;jj<=11;jj++)
						{
							if(a[ii][jj]=='@')
							{
								continue;
							}
							a[ii][jj]=fuzhuxian;
						}
						for(int kk=ii;kk>=3;kk--)
						{
							for(int jj=2;jj<=11;jj++)
							{
								if(a[ii][jj]=='@')
								{
									continue;
								}
								mapp[kk][jj]=mapp[kk-1][jj];
								a[kk][jj]=a[kk-1][jj];
							}
						}
					}
				}
				cou();
				if(maxfs<fs)
				{
					maxfs=fs;
				}
			}
		}
		if(KEY_DOWN('Z'))
		{
			cout<<endl<<"    作者:何大帅"<<endl;
			cout<<"    据说他曾打败宇宙究极无敌暴龙战士..."<<endl;
		}
		if(KEY_DOWN('S'))
		{
			system("cls");
			cout<<endl<<"  1 打开预设落点"<<endl<<endl<<"  2 关闭预设落点"<<endl<<endl<<"    3 退出";
			while(1)
			{
				if(KEY_DOWN('1'))
				{
					ysld=1;
				}
				if(KEY_DOWN('2'))
				{
					ysld=0;
				}
				if(KEY_DOWN('3'))
				{
					UI=1;
					break;
				}
			}
		}
	}
	return 0;
}
